export enum DeclarationsMutationTypes {
    SET_DECLARATIONS = 'SET_DECLARATIONS',
    SET_DECLARATION_RESULT = 'SET_DECLARATION_RESULT',
    SET_DECLARATION_LOADING = 'SET_DECLARATION_LOADING',
  }
  