export enum PersonalMutationTypes {
    SET_CUSTOMER = 'SET_CUSTOMER',
    SET_CUSTOMER_AGES = 'SET_CUSTOMER_AGES',
    SET_CUSTOMER_MEMBERS = 'SET_CUSTOMER_MEMBERS',
    SET_CUSTOMER_RESULT = 'SET_CUSTOMER_RESULT',
    SET_CUSTOMER_LOADING = 'SET_CUSTOMER_LOADING',
  }
  